name = "joja-capital"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "joja-capital-db"
database_id = "f7fb1575-0630-4837-ad71-469c943bf39d"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "joja-capital-images"
